### ISSUE TITLE
Validation using test set

### ISSUE THREAD

**Issue by JungHunOh** [zysong0113/SAVC#4]
Hello, thank you for the motivating work.

I noticed that in the code, the final model in the base session seems to be validated using the test set.
I'm aware that some previous works, such as CEC in CVPR2021, have the same issue.
In my opinion, this convention strikes me as rather unusual and raises concerns about fairness.
I would like to hear your opinion on this concern.

**Comment by zysong0113** [comment]
Hello, thank you for your constructive advice. 
I agree with you, and we do follow the previous setting (e.g., CEC) to validate the model by the testing set to select the best one in the base session, only in order to compare with these SOTA methods.
However, we observe that the performance only slightly changes on both the training and testing set during the later epochs in our training log. 
Thus, this convention does not actually have a significant impact on our method or the final performance, and we also suggest to use the model of the final epoch for incremental update rather than the best one on the testing set.
